[aliases]
TelegramDesktop = "Telegram"
"Org.gnome.Nautilus" = "Nautilus"
"gimp-\\d\\.\\d\\d" = "Gimp"
"Gimp-\\d\\.\\d\\d" = "Gimp"

[icons]
# fontawesome
firefox = ""
Google-chrome = ""
Inkscape = ""
Gimp = ""
Termite = "󰞷"
Alacritty = "󰞷"
Gnome-terminal = "󰞷"
Remote-viewer = "󰖳"
TelegramDesktop = "󰔁"
Code="󰨞"

[general]
separator = "  "
default_icon = "󰘔"

[options]
remove_duplicates = true
no_names = true

